# Generated by Django 6.0.3 on 2026-10-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_bp', models.PositiveIntegerField()),
                ('diastolic_bp', models.PositiveIntegerField()),
                ('pulse', models.PositiveIntegerField()),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=4)),
                ('spo2', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('device', 'Device (simulated)')], default='manual', max_length=10)),
                ('measured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='triage.patient')),
            ],
            options={
                'ordering': ['-measured_at', '-id'],
            },
        ),
    ]
