# Generated by Django 6.1.2 on 2026-10-09 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.JSONField(default=dict)),
                ('recommendation', models.CharField(choices=[('U1', 'U1 Immediate'), ('U2', 'U2 Urgent'), ('U3 Soon', 'U3'), ('U4 Standard', 'U4'), ('U5 Low', 'U5')], max_length=20)),
                ('effective_level', models.CharField(choices=[('U1', 'U1 Immediate'), ('U2', 'U2 Urgent'), ('U3 Soon', 'U3'), ('U4 Standard', 'U4'), ('U5 Low', 'U5')], max_length=20)),
                ('fired_rules', models.JSONField(default=list)),
                ('news2_breakdown', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('rule_version', models.CharField(max_length=40)),
                ('state', models.CharField(choices=[('waiting', 'Waiting'), ('in_consultation', 'In consultation'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('arrived_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='triage.patient')),
            ],
            options={
                'ordering': ['-arrived_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QueueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('assessment_created', 'Assessment created'), ('clock_advanced', 'Clock advanced'), ('deterioration', 'Deterioration'), ('override', 'Override'), ('state_changed', 'State changed')], max_length=40)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='triage.triageassessment')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='triageassessment',
            index=models.Index(fields=['state', 'effective_level', 'arrived_at'], name='triage_tria_state_485512_idx'),
        ),
        migrations.AddIndex(
            model_name='triageassessment',
            index=models.Index(fields=['patient', '-created_at'], name='triage_tria_patient_f51f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='queueevent',
            index=models.Index(fields=['assessment', '-occurred_at'], name='triage_queu_assessm_03d949_idx'),
        ),
    ]
